defaults:
  - _self_
  - train_configs
  - models/aritra_model

train_csv_file: /kaggle/input/UBC-OCEAN/train.csv
test_csv_file: /kaggle/input/UBC-OCEAN/test.csv
submission_csv_file: /kaggle/working/submission.csv
train_data_dir: /kaggle/input/UBC-OCEAN/train_thumbnails
test_data_dir: /kaggle/input/UBC-OCEAN/test_thumbnails
use_thumbnails: True

tasks:
  - train
  - make_submission
  
tasks_descr:
  train:
    script_id: train.train
    model: ${models.model}
    data_dir: ${train_data_dir}
    csv_file: ${train_csv_file}
    image_size: ${models.image_size}
    batch_size: ${batch_size}
    validation_split: ${validation_split}
    random_seed: ${random_seed}
    epochs: ${epochs}
    lr: ${lr}
    save_weights_file: ${models.weights_file}
    use_thumbnails: ${use_thumbnails}
    crop_size_increment: ${crop_size_increment}

  make_submission:
    script_id: scripts.make_submission
    model: ${models.model}
    model_weights: ${models.weights_file}
    image_size: ${models.image_size}
    test_csv_file: ${test_csv_file}
    test_data_dir: ${test_data_dir}
    submission_csv_file: ${submission_csv_file}
    use_thumbnails: ${use_thumbnails}
