train_data_dir: /kaggle/input/UBC-OCEAN/train_thumbnails
test_data_dir: /kaggle/input/UBC-OCEAN/test_thumbnails
image_size: [1024, 1024]
batch_size: 16
validation_split: 0.2
random_seed: 42
epochs: 10
lr: 0.001
num_classes: 5