train_model:
  type: train.models.make_scratch_model
  image_size: [512, 512, 3]
  num_classes: ${num_classes}
  
image_size: [512, 512]
batch_size: 8
validation_split: 0.1
random_seed: 42
epochs: 3
lr: 0.0001
num_classes: 5
save_model_path: metadata/scratch_model.h5